services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: aggregator
      POSTGRES_PASSWORD: aggregator
      POSTGRES_DB: aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggregator -d aggregator"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  aggregator-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: postgres://aggregator:aggregator@postgres:5432/aggregator?sslmode=disable
      HTTP_PORT: "8080"
      GRPC_PORT: "50051"
      N: "1000"   # интервал генерации пакета в миллисекундах (1 секунда)
      K: "10"     # количество случайных чисел в пакете
      M: "4"      # количество воркеров для обработки
    ports:
      - "8080:8080"
      - "50051:50051"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  postgres_data:
    driver: local
