global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aggregator'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:2112']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

