// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package app

import (
	"time"

	"aggregator/internal/config"
	"aggregator/internal/logging"
)

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggingLogger, err := logging.New(configConfig.LogLevel)
	if err != nil {
		return nil, err
	}
	shutdownManager := NewShutdownManager(30*time.Second, loggingLogger)
	app := New(configConfig, loggingLogger, shutdownManager)
	return app, nil
}
