// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"aggregator/internal/config"
	"aggregator/internal/generator"
	"aggregator/internal/logging"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config, err := provideConfig()
	if err != nil {
		return nil, err
	}
	logger, err := provideLogger(config)
	if err != nil {
		return nil, err
	}
	shutdownManager := provideShutdownManager(logger)
	generatorConfig := provideGeneratorConfig(config)
	source := generator.NewRandomSource(generatorConfig)
	workerPool := provideWorkerPool(config)
	app := New(config, logger, shutdownManager, source, workerPool)
	return app, nil
}

// wire.go:

func provideConfig() (*config.Config, error) { return config.Load() }

func provideLogger(cfg *config.Config) (*logging.Logger, error) {
	return logging.New(cfg.LogLevel)
}

func provideShutdownManager(l *logging.Logger) *ShutdownManager {
	const shutdownTimeout = 30 * time.Second
	return NewShutdownManager(shutdownTimeout, l)
}

func provideWorkerPool(cfg *config.Config) *WorkerPool {
	return NewWorkerPool(cfg.WorkerPoolSize)
}
