// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: aggregator.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MaxValue      float64                `protobuf:"fixed64,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDResponse) Reset() {
	*x = GetByIDResponse{}
	mi := &file_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDResponse) ProtoMessage() {}

func (x *GetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetByIDResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetByIDResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetByIDResponse) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type GetByTimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTimeRangeRequest) Reset() {
	*x = GetByTimeRangeRequest{}
	mi := &file_aggregator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTimeRangeRequest) ProtoMessage() {}

func (x *GetByTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*GetByTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *GetByTimeRangeRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetByTimeRangeRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetByTimeRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GetByIDResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTimeRangeResponse) Reset() {
	*x = GetByTimeRangeResponse{}
	mi := &file_aggregator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTimeRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTimeRangeResponse) ProtoMessage() {}

func (x *GetByTimeRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTimeRangeResponse.ProtoReflect.Descriptor instead.
func (*GetByTimeRangeResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *GetByTimeRangeResponse) GetResults() []*GetByIDResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_aggregator_proto protoreflect.FileDescriptor

const file_aggregator_proto_rawDesc = "" +
	"\n" +
	"\x10aggregator.proto\x12\n" +
	"aggregator\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\x0fGetByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tmax_value\x18\x03 \x01(\x01R\bmaxValue\"s\n" +
	"\x15GetByTimeRangeRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"O\n" +
	"\x16GetByTimeRangeResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.aggregator.GetByIDResponseR\aresults2\xb6\x01\n" +
	"\x11AggregatorService\x12E\n" +
	"\n" +
	"GetMaxByID\x12\x1a.aggregator.GetByIDRequest\x1a\x1b.aggregator.GetByIDResponse\x12Z\n" +
	"\x11GetMaxByTimeRange\x12!.aggregator.GetByTimeRangeRequest\x1a\".aggregator.GetByTimeRangeResponseB/Z-aggregator-service/app/src/api/grpc/pb;grpcpbb\x06proto3"

var (
	file_aggregator_proto_rawDescOnce sync.Once
	file_aggregator_proto_rawDescData []byte
)

func file_aggregator_proto_rawDescGZIP() []byte {
	file_aggregator_proto_rawDescOnce.Do(func() {
		file_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)))
	})
	return file_aggregator_proto_rawDescData
}

var file_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aggregator_proto_goTypes = []any{
	(*GetByIDRequest)(nil),         // 0: aggregator.GetByIDRequest
	(*GetByIDResponse)(nil),        // 1: aggregator.GetByIDResponse
	(*GetByTimeRangeRequest)(nil),  // 2: aggregator.GetByTimeRangeRequest
	(*GetByTimeRangeResponse)(nil), // 3: aggregator.GetByTimeRangeResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_aggregator_proto_depIdxs = []int32{
	4, // 0: aggregator.GetByIDResponse.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: aggregator.GetByTimeRangeRequest.from:type_name -> google.protobuf.Timestamp
	4, // 2: aggregator.GetByTimeRangeRequest.to:type_name -> google.protobuf.Timestamp
	1, // 3: aggregator.GetByTimeRangeResponse.results:type_name -> aggregator.GetByIDResponse
	0, // 4: aggregator.AggregatorService.GetMaxByID:input_type -> aggregator.GetByIDRequest
	2, // 5: aggregator.AggregatorService.GetMaxByTimeRange:input_type -> aggregator.GetByTimeRangeRequest
	1, // 6: aggregator.AggregatorService.GetMaxByID:output_type -> aggregator.GetByIDResponse
	3, // 7: aggregator.AggregatorService.GetMaxByTimeRange:output_type -> aggregator.GetByTimeRangeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aggregator_proto_init() }
func file_aggregator_proto_init() {
	if File_aggregator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregator_proto_rawDesc), len(file_aggregator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_proto_goTypes,
		DependencyIndexes: file_aggregator_proto_depIdxs,
		MessageInfos:      file_aggregator_proto_msgTypes,
	}.Build()
	File_aggregator_proto = out.File
	file_aggregator_proto_goTypes = nil
	file_aggregator_proto_depIdxs = nil
}
