package domain

// DataPacket groups a batch of measurements generated by the background
// generator before they are processed by the worker pool.
type DataPacket struct {
	ID           string
	Measurements []Measurement
}
