openapi: 3.0.3
info:
  title: Aggregator REST API
  version: 1.0.0
  description: REST interface for accessing aggregated measurement statistics.
servers:
  - url: http://localhost:8080
paths:
  /max:
    get:
      summary: Retrieve the maximum measurement.
      description: >-
        Returns the maximum measurement either for a single source identified by UUID or for
        all sources within the specified time interval. Exactly one of the following must be provided:
        `id`, or both `from` and `to`.
      parameters:
        - in: query
          name: id
          schema:
            type: string
            format: uuid
          description: Identifier of the source to query.
        - in: query
          name: from
          schema:
            type: string
            format: date-time
          description: Start of the time interval (inclusive).
        - in: query
          name: to
          schema:
            type: string
            format: date-time
          description: End of the time interval (inclusive).
      responses:
        '200':
          description: Maximum measurement found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaxResponse'
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Measurement not found for the given filters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    MaxResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        value:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
      required:
        - id
        - value
        - timestamp
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
          format: int32
      required:
        - error
        - code
